### ISSUE TITLE
Make repository public

### ISSUE THREAD

**Issue by sujen1412** [USCDataScience/polar-domain-discovery#1]
@karanjeets @chrismattmann 
Is there any reason why this repository is private ? 
I am trying to build a docker installable domain discovery system and would like to git clone this repository without any credentials.

**Comment by chrismattmann** [comment]
Let's make it public

**Comment by sujen1412** [comment]
@chrismattmann I do not seem to have the permission to do that. @karanjeets is this something you can do ? 
Thanks

**Comment by karanjeets** [comment]
The repository is now public!
